// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ysjhvtefwhhdjxbhdqwe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlzamh2dGVmd2hoZGp4YmhkcXdlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3Mjc2NDEsImV4cCI6MjA2OTMwMzY0MX0.D31Pc7TLTbeQu18XLvLlcPfUPPrizt6qcW1UjW1-Pjo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});