// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://idkjpgtkxixpglxztchi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlka2pwZ3RreGl4cGdseHp0Y2hpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3MjQyODgsImV4cCI6MjA2OTMwMDI4OH0.cvs44x6Njh8i2motxROupGCgfy0sH7AnHHnjpVeW4-o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});